### ISSUE TITLE
Fatal error: Class 'phpixie_Controller'

### ISSUE THREAD

**Issue by leokun** [PHPixie/Project#1]
Hi,
Today I've just try PHPixie for the first time trying to follow the 30 min tutorial page.

I cant even make it work without changing anything, I have an "Fatal error: Class 'phpixie_Controller' not found in C:\www\phpixie\system\classes\request.php on line 90" just by trying to access to http://localhost/phpixie/

is there any solution ?

regards, Leo

**Comment by dracony** [comment]
Well you should have installed PHPixie into your webroot so that http://localhost/ would be phpixies folder.
It seems you placed the filles into /phpixie/ folder inside the root folder.

**Comment by moonstruck** [comment]
Using virtual host will serve the purpose.
I think installing on sub directories should be added on next release.

**Comment by dracony** [comment]
I'll do some changes to allow subfolder installations in a day or so

**Comment by svpernova09** [comment]
Would this issue be causing a "No input file specified." when installed to a subdomain?

**Comment by dracony** [comment]
You are using PHP-FPM aren't you? If so try changing the last  line of .htaccess  from:
RewriteRule .\* index.php/$0 [PT,L,QSA]
To
RewriteRule .\* index.php?$0 [PT,L,QSA]

**Comment by svpernova09** [comment]
That got me, thanks! Sorry for hijacking this issue.

**Comment by dracony** [comment]
Glad to help. this has actually been posted on the forums a while ago =) You might get an answer sooner if you post it there the next time =)

**Comment by dracony** [comment]
The fix can now be found here:
http://phpixie.com/tutorials/general-information/
