### ISSUE TITLE
Inconsistent Styling

### ISSUE THREAD

**Issue by philsturgeon** [PHPixie/Project#10]
Super random styling on the code for brackets and indentation:

http://d.pr/i/Vtz7

**Comment by dracony** [comment]
how is this random?

**Comment by philsturgeon** [comment]
Projects normally conform to Allman, or BSD KNF style, but you see to have invented your own where its different each time.

**Comment by dracony** [comment]
Actually I myself follow the oldschool K&R stuff. There has been a commit that used an autoformatter that brought it to more or less Allman form, but fixed the indentation issues. I'm moving it back to K&R though.

**Comment by philsturgeon** [comment]
Sweet, just pick one and use it everywhere. CS-Fixer will dot hat for you, but don't have half and half like this :)

**Comment by dracony** [comment]
I tried using PEAR PHP_Beautifier, but i could never customize it enough sadly.

**Comment by philsturgeon** [comment]
CodeSniffer and CS-Fixer will do this for you.  

## 

Phil Sturgeon

**Comment by ghost** [comment]
True. Why not [PSR-1](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-1-basic-coding-standard.md) and [PSR-2](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md)?

**Comment by dracony** [comment]
Well I kinda like K&R style and snake_case (or whatever its called) and at the time of making PHPixie PSR-1/2 were only in the making so I didnt pay much attenion to those. I could rewrite it using PSR-1/2 (actually I think I could just run one of the many tools to do that for me)  but changing method names would obviously break everyones code.

**Comment by philsturgeon** [comment]
Did you start development 14 months ago?

**Comment by dracony** [comment]
Well I was doing it at my leisure since last July though I made the site around December. I dont think PSR-2 was here 14 months ago, as I still kinda remember the whole tabs/spaces holywar being quite recent (half a year ago maybe?)

**Comment by philsturgeon** [comment]
PSR-2 predates PHPixie, you just hadn't heard about it then.

The tabs/spaces war has been ongoing for 20+ years.

**Comment by dracony** [comment]
Just checked, yup you're right =) It's been for there for some time
