### ISSUE TITLE
Routing is extremely confusing

### ISSUE THREAD

**Issue by philsturgeon** [PHPixie/Project#13]
Based on the documentation I have no real idea how routing works.

It seems that only basic routing has been implemented, with no support for callbacks or RESTful URLs.

Simply implementing the [Symfony2 Routing Component](http://symfony.com/doc/2.0/components/routing/introduction.html) would take care of all of that, and you can wrap it up however you like if their API is no good for your PHPixie users.

**Comment by dracony** [comment]
What do you mean by callbacks? Specifying a method instead of a regexp route? If so, that is both implemented and inside the tutorial.

I don't really believe in making routes aware of the HTTP method, always felt it's a controllers job to do this.
