### ISSUE TITLE
API docs are broken

### ISSUE THREAD

**Issue by philsturgeon** [PHPixie/Project#14]
Some pages are white-screens: http://d.pr/i/ybvJ

Some are just empty: http://d.pr/i/rLrK

**Comment by dracony** [comment]
Can't really reproduce those. Are you still getting them?

**Comment by philsturgeon** [comment]
Yeah, try this one http://phpixie.com/api/class-Facebook_Auth_Controller.html

**Comment by dracony** [comment]
But where did you get that link?
It's not on: http://phpixie.com/api/package-Auth.html

**Comment by philsturgeon** [comment]
Go to the root of the api docs:  

http://d.pr/i/ufMu

There are loads more links there than once you've clicked onto a valid package. Most of them are broken.  

## 

Phil Sturgeon

**Comment by dracony** [comment]
That's actually a bug in Apigen. It added excluded classes tot he list. I'll submit the issue to them.
I normally exclude sample controllers and test classes from API generation. But they got to be in the list.
thanks
