### ISSUE TITLE
Disallowing Order By RAND()

### ISSUE THREAD

**Issue by philsturgeon** [PHPixie/Project#17]
By forcing two arguments and throwing an exception if its not asc or desc you are disallowing the perfectly valid `ORDER BY RAND()` syntax.

**Comment by dracony** [comment]
Order by rand() == Order by rand() ASC

I probably should make the direction be ASC by default, that's all, I'll do that,

**Comment by philsturgeon** [comment]
make it optional, instead. Default of null as ASC is inferred when using ORDER BY foo anyway.  

## 

Phil Sturgeon

**Comment by dracony** [comment]
That might be a good way true, no real difference really
