### ISSUE TITLE
Repeating things that have the same result

### ISSUE THREAD

**Issue by philsturgeon** [PHPixie/Project#18]
You do this sort of thing a lot:

```
(strtolower($p[0]) == 'or' || strtolower($p[0]) == 'and')
```

That really should be:

```
(in_array(strtolower($p[0]), array('or', 'and'))
```

Actually it should be:

```
(in_array(strtolower($p[0]), array('or', 'and', 'xor'))
```

Gotta have that XOR.

https://github.com/dracony/PHPixie/blob/master/modules/database/classes/database/query.php#L380

**Comment by dracony** [comment]
Well 2 comparisons (from which 50% of time only a single one executes) are a tad faster than declaring an array and running and in_array on it. I really want to have efficient code. Though I really should've assigned strtolower to some variable beforehand.
XOR, really? why?

**Comment by philsturgeon** [comment]
A variable is fine, as long as you're not repeating yourself. 

Any why not XOR? It's a valid logical operator, why specifically disallow it when you could allow it?

**Comment by dracony** [comment]
Well for one can't really think of a good case were I'd need it. ))

**Comment by philsturgeon** [comment]
That would only be important if you are the only person using your framework.

**Comment by dracony** [comment]
Can you come up with a good case for that?
Because if not I can rhink of a lot more awesome operators that might come useful once

**Comment by philsturgeon** [comment]
What other operators have you got? MySQL doesn't have any more:

https://dev.mysql.com/doc/refman/5.0/en/logical-operators.html

And why are you explicitly trying to block a valid operator? 

http://www.w3resource.com/mysql/logical-operators/xor-operator.php

**Comment by dracony** [comment]
Ah you ment that)))
I misunderstood for the kind of XOR i saw in one of the DB frameworks (basically it constructed the xor using and and or statements), yeah sure, that one should be there)

**Comment by sparksp** [comment]
You don't have to use the one liners that @philsturgeon has mentioned, you could just execute the strtolower on a previous line.

```
if (is_string($p[0]) && isset($p[1]) && is_array($p[1]))
{
    $logic = strtolower($p[0])
    if ($logic == 'and' || $logic == 'or' || $logic == 'xor') {
        $cond = $this->get_condition_part($p[1]);
        $cond['logic'] = $logic;
        return $cond;
    }
}
```

But sometimes readability and maintainability are more important than execution speed.  Reading the rest of that function gives me a headache the more I try to figure out what's going on.  There's no comments, or conveniently named sub-functions... good luck understanding this quickly after not looking at it for a month.

**Comment by dracony** [comment]
Well for starters $p[0] can also be an array, so I can't really call strtolower externally.
I could do this though:
     if (is_string($p[0]) && (($lower=strtolower($p[0])) == 'or' || $lower == 'and')

This way I don't execute any unnecessary stuff

**Comment by philsturgeon** [comment]
Whatever, I think you got the point.  

## 

Phil Sturgeon

**Comment by dracony** [comment]
fixed
