### ISSUE TITLE
PHPixie in a subfolder

### ISSUE THREAD

**Issue by thejw23** [PHPixie/Project#21]
Phpixie url: http://localhost/phpixie/web (no vhost)

Is there any setting like 'base_url'   => '/' in Kohana, that allows me (along with .htaccess RewriteBase) to have Phpixie in a subfolder ?

I looked for it, but it looks like it is missing - witch is an issue, since routes will work after adding 'phpixie/web/, but sending form from sample app end up not on /localhost/phpixie/web/ but on /localhost/

**Comment by dracony** [comment]
There is a guide to doing this here: http://phpixie.com/tutorials/general-information/
tell me if it works for you

**Comment by thejw23** [comment]
Thanks, I  missed that :)
