### ISSUE TITLE
where is vendor folder?

### ISSUE THREAD

**Issue by e-oz** [PHPixie/Project#22]
Hi. 
I can't find "vendor" in github repository, so just to look code I have to find somewhere URL http://phpixie.com/, find here how to download, unpack zip-archive, run IDE and only then look at the code of this framework.

**Comment by dracony** [comment]
Well composer will create the vendor folder for you. This is just the skeleton project.
To download the sources you need to run "php composer.phar install -o --prefer-dist"

The instructions are presnt here: http://phpixie.com/tutorials/download-instructions/
Or is there any particular reason you don't want to use composer?

**Comment by e-oz** [comment]
That exactly is a problem. Just to view code (if it bad or not), I have to use heavy things like installation of project.
Official github repo as a "skeleton" without source code looks... strange.

**Comment by dracony** [comment]
Well the code is split into packages, e.g.:
https://github.com/dracony/PHPixie-Core
https://github.com/dracony/PHPixie-ORM
etc.

The idea is that using composer always gets you the latest version.
But every 4 hours a snapshot with core, db and orm packages in generated here:
http://phpixie.com/phpixie.zip

so if you don't want to use composer you can just download the generated skeleton with the vendor folder included.

**Comment by e-oz** [comment]
1. Links to Core and ORM repositories will be much more interesting, than link to this repository, which is empty.
2. Please, read initial message in this issue. For external visitor (like me), "just download" and then "just unpack", "just run IDE" - it all is too many movements required just to view your code and I'm not sure that my time will not be wasted. Visitor will just say "mmm... nothing here. Ok, close tab".
   Bye.

**Comment by dracony** [comment]
Ah, true. I will update the Readme.md to provide links to package repositories, so it will be easier for developers to find them.
