### ISSUE TITLE
DB class (fields)

### ISSUE THREAD

**Issue by alameya** [PHPixie/Project#26]
When i call
    ->fields('id', 'alias')
    ->fields('name', 'alias2')

result contain 'alias2' field only...

**Comment by dracony** [comment]
Calling fields() overrides the previous setting (just like table() does), You should be doing:
->fields(array('id','alias'), array('name','alias2')) to define aliases

**Comment by alameya** [comment]
i found another bug.
when i wrote abstract layer for DB i tried call  fields(func_get_args()) 
and have exception "explode() expects parameter 2 to be string, array given" on line 65
vendor/phpixie/db/classes/PHPixie/DB/PDO/Query.php

i fixed that by 
        $args = func_get_args();
        $p = array_pop($args);
on line 159
vendor/phpixie/db/classes/PHPixie/DB/Query.php

**Comment by dracony** [comment]
Well I guess you should've done call_user_func_array(array($query,'fields'), func_get_args())
fields() doesnt expect an array of fields, so you can't call it by  fields(func_get_args()) 

Your fix would actually break things like ->fields('id','name') (when you need to select 2 columns)
