### ISSUE TITLE
SQL Syntax error on PDO delete query for Postgres

### ISSUE THREAD

**Issue by darkdino** [PHPixie/Project#30]
DELETE statements built by the PDO Query builder class cause an SQL Syntax error when executed against a PostgreSQL database.

Buy quickly looking at the code, I'd suggest to use the same DELETE query template for pgsql as the one used for SQLite. A patch like that works for me.

**Comment by dracony** [comment]
Thanks, I'll take a look into thiss.

**Comment by dracony** [comment]
Can you post an example of a delete query that causes this? It should generate same queries for both SQLite and PostgreSQL actually.
