### ISSUE TITLE
ORM: how to clone object?

### ISSUE THREAD

**Issue by philosophocat** [PHPixie/Project#32]
Is there an elegant way to copy object? There is no clone() or copy() method in api, how can i create, for example, $pixie_twin from $pixie?

**Comment by dracony** [comment]
Version 2 or 3 ?

**Comment by philosophocat** [comment]
I'm on 2 now, but, please, describe both of them )

**Comment by ghost** [comment]
In 2, just use the 'clone' PHP statement: $query2 = clone $query;

In 3 there really is no need to do it, since the entities should be the same instance anyway, and the queries don't have any state at all =)
