### ISSUE TITLE
Using the ORM from the console.

### ISSUE THREAD

**Issue by whitebook** [PHPixie/Project#40]
I was wondering if there is a way to use the orm from the console?

**Comment by dracony** [comment]
Sure. Within a PHPixie project? Or as a standalone component?

**Comment by whitebook** [comment]
Standalone

**Comment by dracony** [comment]
Replying in the chat =)

**Comment by whitebook** [comment]
$slice = new \PHPixie\Slice();
$database = new \PHPixie\Database($slice->arrayData(array(
    'default' => array(
        'driver' => 'pdo',
        'connection' => 'sqlite::memory:'
    )
)));
$orm = new \PHPixie\ORM($database, $slice->arrayData(array(
    // your config
)));
// and use it
$orm->repository('user').....
