### ISSUE TITLE
Unexpected behaviour: database config loads only from /assets/config dir

### ISSUE THREAD

**Issue by rakshazi** [PHPixie/Project#41]
Hello!

Code `$builder->components()->database()->get('anything')` throws exception:

```
PHPixie\Database\Exception\Driver: Driver '' does not exist

81         $driverName = $config->get('driver');
82         if (!array_key_exists($driverName, $this->driverClasses)) {
>>             throw new \PHPixie\Database\Exception\Driver("Driver '$driverName' does not exist");
84         }
85 

#0 /var/www/vendor/phpixie/database/src/PHPixie/Database.php:83
#1 /var/www/vendor/phpixie/database/src/PHPixie/Database.php:28
    PHPixie\Database->configDriverName(Slice)
#2 /var/www/bundles/app/src/Project/App/Processors/Grabber.php:33
    PHPixie\Database->get('goodhack_cf')
#3 /var/www/bundles/app/src/Project/App/Console/Download.php:42
    Project\App\Processors\Grabber->process('goodhack_cf')
#4 /var/www/vendor/phpixie/console/src/PHPixie/Console/Runner.php:43
    Project\App\Console\Download->run(Slice, Slice)
#5 /var/www/vendor/phpixie/console/src/PHPixie/Console/Runner.php:28
    PHPixie\Console\Runner->runCommand('app:download', array[1], array[0], true)
#6 /var/www/vendor/phpixie/console/src/PHPixie/Console.php:19
    PHPixie\Console\Runner->runFromContext()
#7 /var/www/vendor/phpixie/framework/src/PHPixie/Framework/Console.php:35
    PHPixie\Console->runCommand()
#8 /var/www/vendor/phpixie/framework/src/PHPixie/Framework.php:61
    PHPixie\Framework\Console->processSapiCommand()
#9 /var/www/console:8
    PHPixie\Framework->processConsoleSapiCommand()

Logged items:
```

When database config located in /bundles/app/assets/config/database.php, but all ok when file located in /assets/config/database.php, because $config->data for \PHPixie\Database::__construct() will be null in first case and contains data in second case

Expectected behaviour:
Configuration loads from /assets/config dir and after these loads from /bundles/app/assets/config dir

**Comment by dracony** [comment]
Sorry, just noticed this now. 

Is the problem still there?

**Comment by rakshazi** [comment]
Yep

ср, 26 окт. 2016 г., 17:48 Roman Tsiupa notifications@github.com:

**Comment by dracony** [comment]
I see, actually

/bundles/app/assets/config/database.php is the configuration file for the bundle, not for the framework. They are not supposed to get merged really. This is for things that are only needed for your bundle. Like for example if you have a bundle that uses guzzle and you need to store the configuration somewhere which is not project-related.

Can you tell me what you want to achieve, and I'll try to help you to do it =)

**Comment by rakshazi** [comment]
Ok, here is my case:
I have `app` bundle. This bundle need connect to multiple databases (and db hosts) in some cases. But this configuration needed only for this bundle, not for all project, that's why I expect that `database.php` configuration located in bundle scope will be available only in this scope (such as `private` methods and properties are available only in their's class).
